sudo: required

services:
  - docker

install: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.sonar/installs'

language: java

jdk:
  - oraclejdk8

addons:
  - sonarqube: true
  
before_script:
  - docker run -d -p 3306:3306 -e MYSQL_USER=simple -e MYSQL_PASSWORD=jta -e MYSQL_DATABASE=trans -e MYSQL_ROOT_PASSWORD=secret mariadb:10.3
  - docker run -d -p 5432:5432 -e POSTGRES_USER=simple -e POSTGRES_PASSWORD=jta -e POSTGRES_DB=trans postgres:9.6 

script:
  - openssl aes-256-cbc -k $GPG_PASSPHRASE -in codesigning.asc.enc -out codesigning.asc -d
  - gpg --fast-import codesigning.asc
  - mvn --settings settings.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent deploy sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=$SONAR_ORGANIZATION -Dgpg.passphrase=$GPG_PASSPHRASE

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: 
    - 'target/simple-jta-*.jar'
    - 'target/simple-jta-*.asc'
  skip_cleanup: true
  on:
    tags: true
